name: chatops
on:
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ master ]
  # issue_comment:
  #   types: [created]


env:
  ACR_REGISTRY: 'kubeflowyoacr'
  ACR_REPOSITORY: 'mexicanfood'

jobs:
  code_quality_checks:
    if: contains(github.event.comment.body, '/build-pipeline') || github.event_name != 'issue_comment' 
    runs-on: ubuntu-latest
    steps:
    - run: echo "this is code_quality_checks"

  ci:
    runs-on: ubuntu-latest
    needs: code_quality_checks
    if: github.event_name == 'push' || github.event_name == 'issue_comment'
    steps:
    - run: echo "ci"    

  